### ISSUE TITLE
How should I get the Quantitative results for the previous model in rows 1-3 of TABLE 3

### ISSUE THREAD

**Issue by Full-Adder** [WendongZh/continual_visual_control#1]
Hello, thank you for making such a wonderful paper. As the title suggests, it is not clear to me how the Quantitative results of the previous work were trained to obtain them, was it through continuous learning or general joint training?
![image](https://user-images.githubusercontent.com/49706419/231727053-9a8beff4-ee50-487e-835b-936f40ef1fbe.png)

**Comment by WendongZh** [comment]
The results in the line 1 to 3 are all obtained via continual training. We directly use their released code and train them in a continual manner.
